[package]
name = "tikv"
version = "4.0.0-alpha"
authors = ["The TiKV Authors"]
description = "A distributed transactional key-value database powered by Rust and Raft"
license = "Apache-2.0"
keywords = ["KV", "distributed-systems", "raft"]
homepage = "https://tikv.org"
repository = "https://github.com/tikv/tikv/"
readme = "README.md"
edition = "2018"
publish = false

[features]
default = ["tikv_alloc/default"]
tcmalloc = ["tikv_alloc/tcmalloc"]
jemalloc = ["tikv_alloc/jemalloc", "engine/jemalloc"]
mimalloc = ["tikv_alloc/mimalloc"]
portable = ["engine/portable"]
sse = ["engine/sse"]
mem-profiling = ["tikv_alloc/mem-profiling"]
profiling = ["profiler/profiling"]
failpoints = ["fail/failpoints"]

[lib]
name = "tikv"

[[test]]
name = "failpoints"
path = "tests/failpoints/mod.rs"
required-features = ["failpoints"]

[[test]]
name = "integrations"
path = "tests/integrations/mod.rs"

[[bench]]
name = "raftstore"
harness = false
path = "benches/raftstore/mod.rs"

[[bench]]
name = "coprocessor_executors"
harness = false
path = "benches/coprocessor_executors/mod.rs"

[[bench]]
name = "hierarchy"
harness = false
path = "benches/hierarchy/mod.rs"

[[bench]]
name = "misc"
path = "benches/misc/mod.rs"

[[bench]]
name = "deadlock_detector"
harness = false
path = "benches/deadlock_detector/mod.rs"

[dependencies]
log = { version = "0.3", features = ["max_level_trace", "release_max_level_debug"] }
slog = { version = "2.3", features = ["max_level_trace", "release_max_level_debug"] }
slog-async = { version = "2.3", default-features = false }
slog-global = { version = "0.1", git = "https://github.com/breeswish/slog-global.git", rev = "91904ade" }
slog-term = "2.4"
slog_derive = "0.1"
byteorder = "1.2"
rand = "0.6.5"
quick-error = "1.2.2"
tempfile = "3.0"
time = "0.1"
toml = "0.4"
libc = "0.2"
crc = "1.8"
fs2 = "0.4"
spin = "0.5"
protobuf = "2.8"
nix = "0.11"
utime = "0.2"
chrono = "0.4"
lazy_static = "1.3"
backtrace = "0.2.3"
url = "1.7.2"
sys-info = "0.5.7"
futures = "0.1"
futures-cpupool = "0.1"
futures-locks = "0.1"
tokio-core = "0.1"
tokio-timer = "0.2"
tokio-executor = "0.1"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
zipf = "5.0.1"
bitflags = "1.0.1"
fail = "0.3"
uuid = { version = "0.6", features = [ "serde", "v4" ] }
grpcio = { version = "0.5.0-alpha.3", features = [ "openssl-vendored" ] }
raft = "0.6.0-alpha"
crossbeam = "0.5"
derive_more = "0.11.0"
hex = "0.3"
more-asserts = "0.1"
hyper = { version = "0.12", default-features = false, features = ["runtime"] }
tokio-threadpool = "0.1.13"
tokio-fs = "0.1.6"
tokio-io = "0.1.12"
vlog = "0.1.4"
mime = "0.3.13"
farmhash = "1.1.5"
failure = "0.1"
tipb = { git = "https://github.com/pingcap/tipb.git" }
kvproto = { git = "https://github.com/wujy-cs/kvproto.git" }

tikv_alloc = { path = "components/tikv_alloc", default-features = false }
tikv_util = { path = "components/tikv_util" }
log_wrappers = { path = "components/log_wrappers" }
engine = { path = "components/engine" }
tidb_query = { path = "components/tidb_query" }
pd_client = { path = "components/pd_client" }

[dependencies.murmur3]
git = "https://github.com/pingcap/murmur3.git"

[dependencies.prometheus]
version = "0.4.2"
default-features = false
features = ["nightly", "push", "process"]

[dependencies.prometheus-static-metric]
version = "0.1.4"
default-features = false

[replace]
# Replace openssl with libressl
"openssl-src:111.3.0" = { git = "https://github.com/BusyJay/libressl-src.git" }
# TODO: remove this when slog is compatible with the log 0.4
"log:0.3.9" = { git = "https://github.com/busyjay/log", branch = "use-static-module" }
"log:0.4.6" = { git = "https://github.com/busyjay/log", branch = "revert-to-static" }
# TODO: remove this when new raft-rs is published.
"raft:0.6.0-alpha" = { git = "https://github.com/pingcap/raft-rs", branch = "master" }
"raft-proto:0.6.0-alpha" = { git = "https://github.com/pingcap/raft-rs", branch = "master" }
"protobuf:2.8.0" = { git = "https://github.com/nrc/rust-protobuf", branch = "v2.8" }
"protobuf-codegen:2.8.0" = { git = "https://github.com/nrc/rust-protobuf", branch = "v2.8" }

[dev-dependencies]
# See https://bheisler.github.io/criterion.rs/book/user_guide/known_limitations.html for the usage
# of `real_blackbox` feature.
criterion = { version = "0.2.11", features=['real_blackbox'] }
arrow = "0.10.0"
rand_xorshift = "0.1"

profiler = { path = "components/profiler" }
panic_hook = { path = "components/panic_hook" }
tipb_helper = { path = "components/tipb_helper" }
tidb_query_datatype = { path = "components/tidb_query_datatype" }
test_util = { path = "components/test_util" }
test_raftstore = { path = "components/test_raftstore" }
test_storage = { path = "components/test_storage" }
test_coprocessor = { path = "components/test_coprocessor" }

[target.'cfg(unix)'.dependencies]
signal = "0.6"

[target.'cfg(target_os = "linux")'.dependencies]
procinfo = { git = "https://github.com/tikv/procinfo-rs" }

[workspace]
members = [
  "fuzz",
  "fuzz/fuzzer-afl",
  "fuzz/fuzzer-libfuzzer",
  "fuzz/fuzzer-honggfuzz",
  "components/test_raftstore",
  "components/test_storage",
  "components/test_coprocessor",
  "components/test_util",
  "components/tikv_alloc",
  "components/match_template",
  "components/codec",
  "components/panic_hook",
  "components/tipb_helper",
  "components/log_wrappers",
  "components/tikv_util",
  "components/tidb_query",
  "components/tidb_query_datatype",
  "components/tidb_query_codegen",
  "components/pd_client",
  "cmd",
]

[profile.dev]
opt-level = 0
debug = 1 # required for line numbers in tests, see tikv #5049
codegen-units = 4
lto = false
incremental = true
panic = 'abort'
debug-assertions = false
overflow-checks = false
rpath = false

[profile.release]
opt-level = 3
debug = false
codegen-units = 1
lto = "thin"
incremental = false
panic = 'abort'
debug-assertions = false
overflow-checks = false
rpath = false

[profile.test]
opt-level = 0
debug = 1 # enable line numbers by default for easy test debugging
codegen-units = 16
lto = false
incremental = true
debug-assertions = true
overflow-checks = true
rpath = false

# The benchmark profile is identical to release, except that lto = false
[profile.bench]
opt-level = 3
debug = false
codegen-units = 1
lto = 'thin'
incremental = false
debug-assertions = false
overflow-checks = false
rpath = false
